### ISSUE TITLE
OIAA Update to database/display fails

### ISSUE THREAD

**Issue by csrcarlson** [code4recovery/pdf#15]
We are unable to push our updates to OIAA from the url
since the IP change made by Dean Collins (our ISP host) - Sunday
https://sheets.code4recovery.org/oiaa

Screenshot would show error 500 - so not included but if necessary, let us know. I do not beleive he changed anyhting on DNS, but I do not know if the programming includes host name resolution or...?

Thank you!

**Comment by joshreisner** [comment]
ah, thanks @csrcarlson ! 

turns out this wasn't related to DNS, it was an unexpected value that we were getting in one random line of the spreadsheet.

![Screen Shot 2021-11-16 at 11 53 24 AM](https://user-images.githubusercontent.com/1551689/142056439-4af84796-5379-4a44-b064-9192c02f130b.png)

try it now, it should be working again
