### ISSUE TITLE
Can we include Zoom Info?

### ISSUE THREAD

**Issue by aeb-denver-CO** [code4recovery/pdf#2]
Is it possible to add the zoom IDs /passwords to the printed PDF? Thank you all.

**Comment by joshreisner** [comment]
Hi @aeb-denver-CO - as discussed at NAATW, this service is only for meetings that meet in person. 

The rationale is that we want this format to be as legible as possible, and our spec for holding online meeting information is optimized for the online experience rather than the printed one. (For example, we don't split out Zoom IDs into their own field, they are in long URLs or phone numbers like `+12324443434#,,#,,1234567890#`.)

Also we believe the majority of users looking for an online meeting will have access to a smartphone or computer.

The exception would be users looking for a phone meeting, and if this becomes a big need, the right solution would be to create a new format, rather than mashing it into the existing format.

**Comment by lloy0076** [comment]
@joshreisner That said, simply hiding online meetings from the PDF (which is what it seems to do) is _surprising_; it would be nice if there were an option where a printout could say:

```
Please see the web-site https://aa-stlawrenceny.org/meetings.
```

For more details.

I suppose a cover page could explain why the online meetings are missing but if one builds a PDF for District 42 at the moment it looks like many meetings simply have closed (i.e., don't exist) which isn't actually true.

**Comment by joshreisner** [comment]
Hi David, this project only creates inside pages for a meeting schedule, not a complete one. Groups are expected to prepend and append pages with a cover, useful links, etc.

Our intergroup in San Jose uses the front page to say "for online meetings, go to https://aasanjose.org/meetings" https://docs.google.com/document/d/11UYsGvD2EWMg2O9iEDAEnJn68tbYbNw4Z-oPtl6l6oI/edit
