### ISSUE TITLE
PDF Generator 500 server error

### ISSUE THREAD

**Issue by meetings03** [code4recovery/pdf#32]
I'm getting a 500 server error when trying to generate a PDF meeting list using pdf.code4recovery.org
https://area03.com
PHP v8.0
TSML 3.14.12
WP 6.11
Plugins: Contact Form 5.7.4, Word Fence 7.9.0, WP Super Cache 1.9.3
PHP settings:
allow_url_fopen = Off
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 30
max_input_time = 60
max_input_vars = 1000
memory_limit = 128M
post_max_size = 48M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php80"
upload_max_filesize = 32M
zlib.output_compression = Off

There are about 3000 meetings in our list. Several months ago I tested the PDF generator and it worked fine. I do not remember what version of TSML was installed at that time.
I have tried making the PDF with all plugins except TSML active, same result, 500 server error.
I get same result if using the link from the plugin to pdf.code4recovery.org or by url to pdf.code4recovery.org

**Comment by joshreisner** [comment]
hey @meetings03 - looks like it was so many meetings that it was hitting the server's `max_execution_time` of 30s. i've updated it to 120s and i think it should work now

**Comment by meetings03** [comment]
Thanks Josh,
That worked with the 2876 meetings in the list.
I tested by generating a couple different sizes and options, everything 
worked as expected.

Thank You for being of service,
Greg S.
Area 03 Meeting List Coordinator

**Comment by joshreisner** [comment]
hi greg, you mentioned in your other ticket #33 that you were hitting a 500 again. i'm moving my reply here since this ticket is about 500 errors you're experiencing.

i've now increased the PHP `memory_limit` from `128M` to `512M` and it appears to be working again. 

the site is struggling to render a PDF for 2886 entries. and `512M` appears to be a hard limit for us. code for recovery may need to explore getting a more expensive plan to increase the limit further

**Comment by meetings03** [comment]
Seems to have solved the issue. I was able to generate a pdf.

Thank You for being of service,
Greg S.
Area 03 Meeting List Coordinator
