### ISSUE TITLE
Any way to dynamically generate a PDF schedule on public website?

### ISSUE THREAD

**Issue by shonuff222** [code4recovery/pdf#71]
With the old version of the schedule generator, we used to point to the URL below on our public facing website and it would generate a schedule on the fly that people could print:
https://aa-ksdist23.org/wp-admin/admin-ajax.php?action=tsml_pdf&width=8.5

How do we link from our public website to the new PDF schedule generator and get the same functionality?  It seems to be an "admin" only thing now with just a button to click and I really don't want to dig into the code.  Can you help me piece together a URL for the new generator that we could link to and would dynamically generate a 8.5"x11" schedule for people to print?

Thanks,
Brett B.
District 23 - Lawrence
Area 25 - Kansas

**Comment by anchovie91471** [comment]
Unfortunately, no. Our PDF service is mainly for site admin use because our infrastructure is only able to handle that level of traffic. 

You're welcome to download & adapt the code to suit your needs. 

I know it isn't dynamic and you'll have to remember to re-generate the PDF when changes are made, but you might simply generate the PDF and make that downloadable from your site as well.

Thank you!
Anthony B.

**Comment by shonuff222** [comment]
No problem, I understand. I appreciate the quick response and your service.

Brett
